[package]
name = "graph_filesystem"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.15.1"
libc = "0.2.174"
log = "0.4.27"
mount-watcher = "0.5.0"
tempfile = "3.20.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
