[package]
name = "drums"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
syn = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
quote = "1"
tracing-test = "0.2.5"
